Cargo.lock
Turns out it was [a regression in rust's type inference](https://github.com/rust-lang/rust/issues/125319) causing the time crate to break. Fix was to update the time crate to 0.3.36 from 0.3.34.
=> Update time dep to fix build

Cargo.lock, Cargo.toml, crates/mod-host/src/host/hook/thunk.rs
`asm!` is no longer allowed in naked fns, so I've swapped it for `naked_asm!`. they have also pulled `MaybeUninit::uninit_array` which dll-syringe uses, so I've added a temporary patch entry to a repo that has a fix included.
=> Accommodate for changes to unstable features

Cargo.lock, crates/mod-host-assets/Cargo.toml, crates/mod-host-assets/build.rs, crates/mod-host-assets/src/alloc.rs, crates/mod-host-assets/src/lib.rs, crates/mod-host-assets/src/mapping.rs, crates/mod-host-assets/src/string.rs, crates/mod-host-assets/src/wwise.rs, crates/mod-host/src/asset_archive.rs
Use cxx-stl to model utf8, 16, 32, sjis and eucjp strings with encoding validation and DLStdAllocator support for resource overrides.
=> Model DLString with cxx-stl and remove cxx dependency

CHANGELOG.md, crates/mod-host/src/lib.rs
The program-wide crash handler for me3_mod_host.dll was dropped as soon as it was assigned. This fix `mem::forget`s its RAII guard.
=> Fix `CrashHandler` being uninstalled via its `Drop` impl

CHANGELOG.md, crates/cli/src/commands/launch.rs, crates/launcher-attach-protocol/src/lib.rs, crates/mod-host-assets/src/dl_device.rs, crates/mod-host/src/asset_hooks.rs, crates/mod-host/src/lib.rs, crates/mod-protocol/src/lib.rs, schemas/mod-profile.json
Extend Nightreign support to all non-wwise files by hooking all overloads of the same function instead of the only one used in earlier games.
Get ready to fix missing sound issues when using overrides for Nightreign only by passing down the `me3_mod_protocol::Game` enum. It still needs more work because the ER/AC6 fix does not work, but the infinite loop is still there.
Closes #98
=> Fix Nightreign file overrides

installer.sh
=> fix(linux): ensure config home exists before creating default config

CHANGELOG.md, crates/mod-host-assets/src/wwise.rs, crates/mod-host/src/asset_hooks.rs
Replaces export polling with scanning for another injection point to avoid the infinite loop bug encountered in fs code. This allows for proper soundbank and wem overrides in NR, and removes the need for the workaround in ER/AC6 that reported any new bnds as having failed to mount.
=> Fix wwise overrides for ER/AC6/NR

Cargo.lock, Cargo.toml, crates/cli/Cargo.toml, crates/mod-host-assets/Cargo.toml, crates/mod-host-assets/src/dl_device.rs, crates/mod-host-assets/src/mapping.rs, crates/mod-host/src/asset_hooks.rs
Normalize all paths with `normpath` and better handle OS-encoded strings.
This addresses an issue where me3 could not provide overrides for a game patched with UXM, where a relative path like `".//////sound/soundbanksinfo.mobnkinfo"` would not be overidden.
Tested on ERR and UXM-patched NR.
=> fix(overrides): UXM disk overrides

.lldbinit, support/lldb/me3.py
Inspired by the WINE DYLD patchset by the Google Stadia team <https://github.com/werat/llvm-project-wine/blob/main/patches/0030-lldb-Add-DYLD-plugin-for-debugging-Wine.patch>.
Attach to a windows process and run the command `load_wine_modules` to load any present Windows modules.
=> feat(dev): support debugging wine executables on linux with LLDB

Cargo.lock, crates/cli/Cargo.toml, crates/mod-host/Cargo.toml, crates/mod-host/src/host.rs, typos.toml
When we load a native mod there's potential for it to raise a Windows exception and crash the mod host. Now we catch that exception and display a warning to the user that the mod may not be working as expected.
=> feat: capture windows exceptions during native mod loads

installer.sh
Make sure we have an interactive terminal before prompting for input.
Fixes #183.
=> fix(linux): prevent prompt spam when creating config file fails

Makefile, installer.sh
The Linux distribution previously downloaded individual binaries from the GitHub release that are no longer available. This update downloads the tarball instead and extracts the needed components from there.
Fixes #196
=> fix: Update Linux installer to use portable distribution

crates/launcher-attach-protocol/src/lib.rs, crates/launcher/src/game.rs, crates/launcher/src/main.rs, crates/mod-host/src/detour.rs, crates/mod-host/src/lib.rs
This exists purely to signal minidump crash events, which are currently not enabled in the latest release. Get rid of the infrastructure for handling it via pipes, and we'll use `WaitForMultipleObjects` on the process/crash event.
Additionally switch the mod host to logging to `stdout`, so we capture logs from any other DLL mods in use.
Fixes #270.
=> fix: Don't block shutdown with monitor thread

crates/cli/src/commands/launch.rs, crates/mod-host-assets/src/mapping.rs
Skip invalid and nonexistent paths in mod profiles before passing them to the mod host, preventing hard errors.
Closes #240
=> fix: Validate mod profile filepaths

Makefile
=> fix(linux): Correctly set mtime of tarball contents

docs/index.md, docs/requirements.in, docs/requirements.txt, mkdocs.yml
A lot of search queries for me3 are written as "mod engine 3", so reference Mod Engine 2 to promote results for users looking for a newer version of ModEngine.
=> chore(docs): Reference Mod Engine2 in docs for Google SEO

mkdocs.yml
中国人 = Chinese (nationality)
中文 = Chinese (language)
Good reference for localised language names is [List of Wikipedias](https://meta.wikimedia.org/wiki/Special:MyLanguage/List_of_Wikipedias)
=> Chinese (language) not Chinese (nationality)

crates/mod-host-assets/src/mapping.rs, crates/mod-host-assets/src/wwise.rs, crates/mod-host/Cargo.toml, crates/mod-host/src/asset_hooks.rs, crates/mod-host/src/filesystem.rs, crates/mod-host/src/lib.rs
During the mod host initialization routine (before loading natives) hook the following functions:
>CreateFileW, CreateFile2, CreateDirectoryW, CreateDirectoryExW, DeleteFileW
This allows for files looked up inside the game directory like mod configs and other files to be loaded from the corresponding mod packages.
=> fix(host): Use filesystem hooks

crates/mod-host/src/debugger.rs, crates/mod-host/src/lib.rs
Address SteamStubDRM calling `NtSetInformationThread` with `ThreadHideFromDebugger` on the main thread (and block `ThreadHideFromDebugger` period)
=> feat: More anti-anti-debug features

crates/cli/src/commands/info.rs, crates/cli/src/commands/launch.rs, crates/cli/src/commands/profile.rs, crates/cli/src/db/profile.rs, crates/mod-protocol/src/lib.rs, crates/mod-protocol/test-data/basic_config.me3.toml.expected, crates/mod-protocol/test-data/plural_packages.me3.expected, crates/mod-protocol/test-data/singular_package.me3.expected, schemas/mod-profile.json
Introduces a special behavior for `disable_arxan`, making it required if either the mod profile or the command line requires it.
=> refactor: Move `disable_arxan` to the mod profile

Cargo.lock, crates/cli/Cargo.toml, crates/cli/src/commands.rs, crates/cli/src/commands/info.rs, crates/cli/src/commands/launch.rs, crates/cli/src/commands/profile.rs, crates/cli/src/config.rs, crates/cli/src/main.rs, crates/launcher/src/main.rs
Edited CLI help for typos, errors, length, language. There is now extended `--help` vs short `-h` for some options. Option descriptions wrap nicely based on terminal width.
=> Clean up CLI help, add nicer wrapping

Cargo.lock, Cargo.toml, crates/mod-protocol/Cargo.toml, crates/mod-protocol/src/dependency.rs, schemas/mod-profile.json
Fixes a bug where profiles with multiple packages and natives did not have a deterministic load order without using the `load_before`/`load_after` keys.
=> fix: Consistent native and package load order

Cargo.lock, crates/cli/Cargo.toml, crates/cli/src/commands/launch.rs, crates/cli/src/commands/launch/proton.rs, crates/mod-host/src/lib.rs
All valid directories that can contain a compatibilitytool.vdf file are now queried for a manifest matching the tool we're interested in. Additionally, we also check the actual name contained in the manifest instead of relying on the name of the directory.
Fixes #425, #426
=> fix(linux): Support proper compatibility tool lookup

crates/mod-host/src/host.rs, crates/mod-host/src/lib.rs
Workaround until `dearxan` is updated to properly handle this data encryption method.
Closes #498
=> fix(host): Missing music and dialogue audio in Dark Souls 3

crates/cli/src/commands/profile.rs, crates/cli/src/db/profile.rs, crates/cli/src/main.rs, installer.nsi
Uniformly handle profile names and paths (a profile mentioned by name as `MyMod2.1` should not be attempted to be loaded as `MyMod2.me3`) and move the package directory creation directives necessary for the installation process into the installer itself. Also add Dark Souls 3 to the installer.
Closes #346
=> fix(cli): Profile improvements

crates/cli/src/commands/launch.rs
Closes #416
Tested with no me3 config in any of the searched paths, and with win bins installed to:
```
/usr/lib64/me3/x86_64-windows/me3_mod_host.dll
/usr/lib64/me3/x86_64-windows/me3-launcher.exe
```
Before:
```console
$ /usr/bin/me3 launch -g er # fails to launch
... ME3_LAUNCHER_HOST_DLL="\"/usr/lib64/me3/x86_64-windows/me3_mod_host.dll\""
... proton" "waitforexitandrun" "/usr/lib64/me3/x86_64-windows/me3-launcher.exe"
```
After:
```console
$ cargo run --release --target x86_64-unknown-linux-gnu --bin me3 launch -g er # ok
... ME3_LAUNCHER_HOST_DLL="\"/run/host/usr/lib64/me3/x86_64-windows/me3_mod_host.dll\""
... proton" "waitforexitandrun" "/run/host/usr/lib64/me3/x86_64-windows/me3-launcher.exe"
```
=> fix(linux): Fix path remapping for SLR
