garyttierney/me3

README.md
docs/.meta.yml
docs/blog/posts/.meta.yml
docs/configuration-reference.md
docs/index.md
docs/user-guide/.meta.yml
docs/user-guide/creating-mod-profiles.md
docs/user-guide/distribution.md
docs/user-guide/installation.md
docs/user-guide/troubleshooting.md
mkdocs.yml

Release documentation

---

.github/codecov.yml
.github/workflows/changelog-check.yml
.github/workflows/checks.yml
.github/workflows/cleanup.yml
.github/workflows/publish.yml
.github/workflows/sbom.yml
crates/cli/src/commands/launch.rs
crates/cli/src/commands/profile.rs
crates/cli/src/main.rs
crates/mod-protocol/src/lib.rs
crates/mod-protocol/src/package.rs
crates/telemetry/src/lib.rs
installer.sh
releng/RELEASE_NOTES.md
releng/bin/create-release
releng/bin/create-release-pr
releng/bin/release-notes

Improve release engineering

---

crates/mod-host/src/asset_hooks.rs

Temporary hotfix to prevent infinite loops with FIXME comment, I will address the actual issue soon.

Warning when loading NR soundbanks and wems

---

.vscode/settings.json
.vscode/tasks.json
Cargo.lock
Cargo.toml
crates/cli/Cargo.toml
crates/cli/src/commands.rs
crates/cli/src/commands/launch.rs
crates/cli/src/commands/profile.rs
crates/cli/src/main.rs
crates/env/Cargo.toml
crates/env/src/lib.rs
crates/launcher/Cargo.toml
crates/launcher/src/game.rs
crates/launcher/src/main.rs
crates/mod-host/Cargo.toml
crates/mod-host/src/host.rs
crates/mod-host/src/lib.rs
crates/telemetry/Cargo.toml
crates/telemetry/src/lib.rs

Complete overhaul of the me3 telemetry approach. Now we support distributed spans, capturing backtraces, and associating telemetry with a release version.

feat: distributed telemetry overhaul

---

CHANGELOG.md
crates/launcher/src/game.rs
crates/launcher/src/main.rs

i.e. when "Run as Administrator" compatability setting is used

Fix error reporting for elevation errors

---

crates/mod-host/src/lib.rs

Supports generating an LLVM profdata file from the mod host if the binaries are instrumented with coverage. This can be used with cargo-llvm-cov to produce coverage reports for launches of the game:
First setup llvm-cov in the build environment to emit profiler data:
Linux
```shell
> $ source <(cargo llvm-cov show-env --export-prefix)
```
Windows
```shell
> $ Invoke-Expression (cargo llvm-cov show-env --with-pwsh-env-prefix | Out-String)
```
Then build and run the game with instrumentation
```shell
> $ cargo llvm-cov clean --workspace
> $ cargo build --all
> $ cargo run -p me3-cli -- launch -g er
```

chore: generate LLVM profdata from mod-host

---

.github/workflows/publish.yml
Makefile
distribution/portable/cross-platform/eldenring-default.me3
distribution/portable/cross-platform/nightreign-default.me3
distribution/portable/linux/launch-eldenring-mods
distribution/portable/linux/launch-nightreign-mods
distribution/portable/windows/launch-eldenring-mods.bat
distribution/portable/windows/launch-nightreign-mods.bat

Adds a packaging process for portable distributions on both Windows and Linux

feat: Create portable distributions

---

crates/cli/src/commands/launch.rs

feat: Support for custom steam compatibility tools

---

crates/cli/src/commands/launch.rs

fix: Ensure 64-bit overlay is injected for Proton

---

README.md

Change "FROMSOTWARE" -> "FROMSOFTWARE"

docs: Fix typo in FROMSOFTWARE

---

mkdocs.yml

I couldn't find a way to reference global properties in the mkdocs.yml file

[Simplified Chinese] analytics and consent localization

---

.vscode/settings.json

Also remove yaml schema association.

chore(dev): Always sign off commits in VS Code

---

docs/configuration-reference.md
docs/configuration-reference.pl.md
docs/configuration-reference.zh.md

docs: Fix typo in example profile

---

crates/cli/src/commands/profile.rs

fix: Don't list non-profile files

---

crates/mod-host/src/lib.rs

fix: Respect Native.optional

---

crates/telemetry/src/lib.rs

fix: Respect NO_COLOR

---

crates/cli/src/commands/launch.rs

If you just point directly to a file in the command line with the profile like so `me3.exe launch -p mods.me3 --auto-detect`, the parent of `mod.me3` will just be an empty path, which `normalize` refuses to handle.
My quick solution for this is to just normalize first, then take the parent of the normalized path.

Fix launch path normalization

---

distribution/linux/install-user.sh

Don't create default config

---

README.md

Also put the games in chronological order.

docs: Add DS3 to supported games

---

.github/ISSUE_TEMPLATE/bug-report.yml
CHANGELOG.md
Cargo.lock
crates/binary-analysis/Cargo.toml
crates/cli/Cargo.toml
crates/env/Cargo.toml
crates/launcher-attach-protocol/Cargo.toml
crates/launcher/Cargo.toml
crates/mod-host-assets/Cargo.toml
crates/mod-host-types/Cargo.toml
crates/mod-host/Cargo.toml
crates/mod-protocol/Cargo.toml
crates/telemetry/Cargo.toml
crates/xtask/Cargo.toml
installer.sh

- [4dbcb4a](https://github.com/garyttierney/me3/commit/4dbcb4ad21ae1957465fd1d0e43a26c531065239) Add DS3 to supported games in [#497](https://github.com/garyttierney/me3/pull/497)
> Also put the games in chronological order.

chore: Release v0.8.0

---

.github/ISSUE_TEMPLATE/bug-report.yml
CHANGELOG.md
Cargo.lock
crates/binary-analysis/Cargo.toml
crates/cli/Cargo.toml
crates/env/Cargo.toml
crates/launcher-attach-protocol/Cargo.toml
crates/launcher/Cargo.toml
crates/mod-host-assets/Cargo.toml
crates/mod-host-types/Cargo.toml
crates/mod-host/Cargo.toml
crates/mod-protocol/Cargo.toml
crates/telemetry/Cargo.toml
crates/xtask/Cargo.toml
installer.sh

- [5b216e7](https://github.com/garyttierney/me3/commit/5b216e75b7b41a78b00fb71dc2403a1c16684011)  *(docs)* Work around blog plugin incompatibility with mkdocs-static-18n
- [004f1e2](https://github.com/garyttierney/me3/commit/004f1e2371cbfd16805f5641fa255fc3c59cb674)  *(host)* Missing music and dialogue audio in Dark Souls 3 in [#516](https://github.com/garyttierney/me3/pull/516)
- [26dde17](https://github.com/garyttierney/me3/commit/26dde172b39f2410dfdc14d61ea7571856013d28) Load natives with initializers in a new thread in [#501](https://github.com/garyttierney/me3/pull/501)
- [8dca989](https://github.com/garyttierney/me3/commit/8dca98979767c6387e75e8ca777a93199faccf0a)  *(feature\)* Collapsible code blocks
- [dd9271f](https://github.com/garyttierney/me3/commit/dd9271f4619038e4b1089aac6e16 …

chore: Release v0.8.1
